package com.codenameone.higherlower;

import static com.codename1.ui.CN.*;
import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;
import com.codename1.io.*;
import com.codename1.ui.plaf.*;
import com.codename1.ui.util.Resources;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class HigherLower extends Lifecycle {
    @Override
    public void runApp() {
        Form game = new Form("Higher Lower Game", BoxLayout.y());

        //int number = (int) (Math.random()*10+1);

        Label info = new Label("I've generated a number between 1 and 10... Try to guess it");

        TextField numberInput = new TextField();
        //int guess = Integer.parseInt(numberInput.getText());

        Button guessButton = new Button("Guess this number");

        game.add(info);

        game.add(numberInput);

        game.add(guessButton);
        guessButton.addActionListener(e -> checkNumber());

        game.getToolbar().addMaterialCommandToSideMenu("Credits",
        FontImage.MATERIAL_CHECK, 4, e -> credits());
        game.show();    // Show the created form
    }

    private void checkNumber() {
    }

    private void credits() {
        Dialog.show("Codename One", "https://start.codenameone.com/\nhttps://start.codenameone.com/\nCode by KampfZomby", "Nice", null);
    }

    private void lower() {
        Dialog.show("Haha wrong number", "The number I search is lower than yours", "OK", null);
    }

    private void higher() {
        Dialog.show("Haha wrong number", "The number I search is higher than yours", "OK", null);
    }

    private void win() {
        Dialog.show("Congratulations", "You found the number!", "Play again", null);
    }

}
