package com.codenameone.higherlower;

import com.codename1.system.Lifecycle;
import com.codename1.ui.*;
import com.codename1.ui.layouts.*;

import java.util.Random;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class HigherLower extends Lifecycle {

    int number;
    int guess;
    int tries;
    TextField numberInput;

    @Override
    public void runApp() {
        Form game = new Form("Higher Lower Game", BoxLayout.y());

        Label info = new Label("Ich habe mit eine Zahl zwischen 1 und 10 ausgedacht.");

        newNumber();

        Button guessButton = new Button("Errate die Zahl");
        numberInput = new TextField();

        game.add(info);

        game.add(numberInput);

        game.add(guessButton);
        guessButton.addActionListener(e -> checkNumber());

        game.getToolbar().addMaterialCommandToSideMenu("Credits",
        FontImage.MATERIAL_CHECK, 4, e -> credits());
        game.show();    // Show the created form
    }

    private void checkNumber() {
        guess = Integer.parseInt(numberInput.getText());
        if (number == guess) {
            win();
        } else if (number > guess) {
            higher();
        } else {
            lower();
        }
    }

    private void credits() {
        Dialog.show("Codename One", "https://start.codenameone.com/\nhttps://start.codenameone.com/\nCode by KampfZomby", "Nice", null);
    }

    private void lower() {
        Dialog.show("Haha falsche Zahl", "Die Zahl die ich suche ist kleiner", "OK", null);
        tries = tries + 1;
    }

    private void higher() {
        Dialog.show("Haha falsche Zahl", "Die Zahl die ich suche ist größer", "OK", null);
        tries = tries + 1;
    }

    private void win() {
        tries = tries + 1;
        Dialog.show("Glückwunsch", "Du hast die Zahl gefunden!\nDafür hast du " + tries + " Versuche gebraucht.", "Nochmal spielen", null);
        newNumber();
        tries = 0;
    }

    private void newNumber() {
        Random random = new Random();
        int max = 10;
        int min = 1;
        number = random.nextInt(max - min + 1) + min;
    }

}
